add pokemon page
faramozzayw/pokemon pull request #3
Opened 2021-02-26 14:23 UTC by faramozzayw

2021-02-26 14:53 UTC, drizzer14 requested changes

2021-02-26 14:53 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.component.tsx
> +              <PokemonСharacteristic title="Height" value={pokemon.height} />
В таких ситуациях `Array.prototype.map` – твой лучший друг. Все уникальные части формируешь в структуру данных и мапишь массив из них на JSX разметку.

2021-02-26 14:53 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +  }
https://lodash.com/docs/4.17.15#padEnd

2021-02-26 14:53 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +// @ts-expect-error
А где тут ошибка и почему?

2021-02-26 14:53 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +  const id = (params?.id as string) ?? '0';
`as string` тут бесполезен.

2021-02-26 14:53 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +  const pokemonRes = await axios.get<Pokemon>(`https://pokeapi.co/api/v2/pokemon/${id}`);
А если тут ошибка будет?

2021-02-26 14:53 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +  const pokemon = pokemonRes.data;
Сразу можно `data` забрать из авейта запроса.

2021-02-26 14:53 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +  } catch {}
Перепиши без мутирования данных и с рабочим блоком `catch`.

2021-02-26 14:53 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +}
`export interface PokemonPageProps extends InferGetServerSidePropsType<typeof getServerSideProps> {}`

2021-02-26 14:53 UTC, drizzer14 commented on src/client/shared/components/pokemon-characteristic/pokemon-characteristic.component.tsx
> +  return (
Не проще ли тогда уже не рендерить этот компонент вообще?

2021-02-26 14:53 UTC, drizzer14 commented on src/client/shared/components/pokemon-characteristic/pokemon-characteristic.styles.ts
> +const Value = styled.kbd`
`const Value = styled(Title).attrs(() => ({
  as: 'kbd'
});`

Можно просто расширить `Value` от `Title`, поменяв элемент.

2021-02-26 14:53 UTC, drizzer14 commented on src/client/shared/components/pokemon-characteristic/pokemon-characteristic.styles.ts
> +const Wrapper = styled.div``;
Зачем это делать стайлд компонентом, если у него нет стилей?

2021-02-26 14:53 UTC, drizzer14 commented on src/client/shared/components/pokemon-type-list/pokemon-type-list.component.tsx
> +export interface PokemonTypeListProps {
`export interface PokemonTypeListProps extends Pick<Pokemon, 'types'>`

2021-02-26 14:53 UTC, drizzer14 commented on src/client/shared/components/pokemon-type-list/pokemon-type-list.component.tsx
> +        <PokemonType key={`${type}`}>{type.name}</PokemonType>
А в чём смысл интерполяции `type`? Возьми оттуда `name` просто.

2021-02-26 14:53 UTC, drizzer14 commented on src/client/shared/components/pokemon-type-list/pokemon-type-list.styles.ts
> +  gap: 10px;
`gap` лучше не использовать, у него поддержка не очень.

2021-03-01 09:41 UTC, faramozzayw commented on src/client/shared/components/pokemon-characteristic/pokemon-characteristic.component.tsx
> +  return (
Так он ведь и [не рендерится](https://reactjs.org/docs/conditional-rendering.html#preventing-component-from-rendering)

2021-03-01 12:06 UTC, drizzer14 requested changes

2021-03-01 12:06 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +  }
Фигня получилась.
У тебя во всей этой функции две ветки – успех и ошибка. Ты их по пути перемешиваешь, называешь разными словами, запутываешь, и в конце через `ts-expect-error` и переназначения из объекта в объект возвращаешь ошибку в успешном результате.
Не кажется странным? Меня эта функция очень запутала, например.

2021-03-01 12:06 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +  }
Зачем тут `for/of`? Если уже лезешь в такую асинхронность, возьми сразу `for await/of` по двум промисам.

2021-03-01 12:06 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +        description: descriptionResult.value.ok ?? null,
Я предлагаю всё-таки заново посмотреть на эту всю функцию, сейчас она выглядит очень запутанно и костыльно.

2021-03-01 12:06 UTC, drizzer14 commented on src/client/shared/components/pokemon-characteristic/pokemon-characteristic.component.tsx
> +    <div>
`article` лучше подошёл бы.

2021-03-01 12:06 UTC, drizzer14 commented on src/client/shared/entity/pokemon.d.ts
> +  description: string | { error: string };
Не мешай ошибки с позитивом. Если тебе надо вернуть ошибку – возвращай её отдельным объектом, не связанным с нормальными данными. Чего тогда в `name` или `id` не запихнуть объект с ошибкой?

2021-03-01 13:58 UTC, faramozzayw commented
#### 📝Changed routes:


| [**/pokemons/\[id\]**](https://pokemon-rcdgkzgi6-faramozayw.vercel.app/pokemons/[id]) |
|:-:|
|<a href="https://pokemon-rcdgkzgi6-faramozayw.vercel.app/pokemons/[id]"><img src="https://images.weserv.nl?url=https://s.microlink.io/_h7XHErGCNPjlWHPww6IQSFQ6DE_.png&w=600" alt="Screenshot of /pokemons/[id]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/cMLMRSA_a0MvZkiBgF5PlP4hZ1k_.png">(view full size)</a> |







Commit b713f21d50a573e22213f3d40bc8c5f07f00e1f3 (https://pokemon-rcdgkzgi6-faramozayw.vercel.app).

2021-03-01 14:10 UTC, drizzer14 requested changes

2021-03-01 14:10 UTC, drizzer14 commented on .env
> +API_URL="https://pokeapi.co/api/v2"
`.env` лучше не коммитить в репу.

2021-03-01 14:10 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.component.tsx
> +  const characteristics: Array<[string, number | undefined]> = [
И зачем в итоге эта переменная? Чтоб один раз из неё новый массив сделать и замапить?

2021-03-01 14:10 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.component.tsx
> +  if (!pokemon) return null;
Я тебе уже писал – делай редирект ещё на сервере. На странице покемона он должен быть всегда, смысл тут рендерить **ничего**?

2021-03-01 14:10 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +  if (Array.isArray(params!.id)) {
Что за  `!.`?
Почему оно может быть массивом?

2021-03-01 14:10 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +    res.setHeader('Location', '/404');
Это не обязательно, достаточно использовать `notFound: true`

2021-03-01 14:10 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +      const description = descriptions.filter(({ language }) => language.name === 'en')[0]?.description;
`find` вместо `filter()[0]`

2021-03-01 14:10 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +    return {
Стилистически лучше `return` начинать после новой строки.

2021-03-01 14:10 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.props.ts
> +            description: null,
Давай по семантике разберёмся.
`null` по смыслу является буквально объектом, который не удалось инициализировать.
`undefined` – отсутствующее значение.

Чем из этого является неуказанная строка `description`?

2021-03-01 15:07 UTC, faramozzayw commented
#### 📝Changed routes:


| [**/pokemons/\[id\]**](https://pokemon-m2fse2q0f-faramozayw.vercel.app/pokemons/[id]) |
|:-:|
|<a href="https://pokemon-m2fse2q0f-faramozayw.vercel.app/pokemons/[id]"><img src="https://images.weserv.nl?url=https://s.microlink.io/1sm5RVpAn_sJrOf1dzudiSJ09kc_.png&w=600" alt="Screenshot of /pokemons/[id]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/urjLqBfICabQz8xCUFPUlI9jofM_.png">(view full size)</a> |







Commit 2c30b433b8dc0fdb887eb5e43581a238a3e45bae (https://pokemon-m2fse2q0f-faramozayw.vercel.app).

2021-03-01 15:10 UTC, faramozzayw commented
#### 📝Changed routes:


| [**/pokemons/\[id\]**](https://pokemon-9ukkpyov7-faramozayw.vercel.app/pokemons/[id]) |
|:-:|
|<a href="https://pokemon-9ukkpyov7-faramozayw.vercel.app/pokemons/[id]"><img src="https://images.weserv.nl?url=https://s.microlink.io/SyoPSfSn6d0S1VLZQSWkS2CllMQ_.png&w=600" alt="Screenshot of /pokemons/[id]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/azGvXHT0b64rTsZEziMKplanzYQ_.png">(view full size)</a> |







Commit e0bb93bcc2472add2b8a636bf6702b573ca2f76f (https://pokemon-9ukkpyov7-faramozayw.vercel.app).

2021-03-01 15:18 UTC, drizzer14 commented on src/client/routes/pokemons/pokemon-page.component.tsx
> +                <PokemonСharacteristic key={title} title={title as string} value={value} />
Чтобы в случаях с такими кортежами не указывать потом везде `as string`, лучше типизировать сам массив как массив кортежей:

```typescript
([
  ['Height', pokemon.height],
  ['Weight', pokemon.weight],
] as Array<[string, number]>).map(...)
```

2021-03-01 15:21 UTC, faramozzayw commented
#### 📝Changed routes:


| [**/pokemons/\[id\]**](https://pokemon-38gmmca75-faramozayw.vercel.app/pokemons/[id]) |
|:-:|
|<a href="https://pokemon-38gmmca75-faramozayw.vercel.app/pokemons/[id]"><img src="https://images.weserv.nl?url=https://s.microlink.io/31KcWccJExKn2bYYCcj734KdIa8_.png&w=600" alt="Screenshot of /pokemons/[id]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/qqEe3K5iou_NZly_IugR_XVNS1I_.png">(view full size)</a> |







Commit 17f8fdb9daf8a6d62d0e25a8f721d046f15545fa (https://pokemon-38gmmca75-faramozayw.vercel.app).

2021-03-01 15:27 UTC, drizzer14 approved these changes

2021-03-01 15:34 UTC, merged