Pokemon pagination
faramozzayw/pokemon pull request #6
Opened 2021-03-03 10:30 UTC by faramozzayw

2021-03-03 10:59 UTC, drizzer14 requested changes

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/home-page.component.tsx
> +};
Не очень мне нравится такое решение, если честно. Надо подумать, как сделать красивше. Например, враппер не над страницей, а непосредственно над её контентом (`children` как функция с передачей контекста, а ля `Context.Consumer`, например).

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/home-page.component.tsx
> +    <PokemonsProvider initPokemons={pokemonsList} initQuery={initQuery}>
`initPokemons` и `initQuery` звучат как названия функций. `initial` лучше бы подошло, имхо.

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/utils.ts
> +export const getPokemons = async (query: Query) => {
Эта функция не похожа на утилиту. Выглядит как часть API страницы. Не уверен, что стал бы такие функции искать в файле `utils`

2021-03-03 10:59 UTC, drizzer14 commented on package.json
> +    "querystring": "^0.2.1",
Тип `ParsedURLQuery` можно достать и без этого пакета.

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/home-page.props.ts
> +  },
Если тебе нужны оба дефолтных ключа из `query`, то лучше их объявление переместить в тело функции. При такой записи у тебя они слетят, как только в `query` попадёт хоть что-то.

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/home-page.props.ts
> +    const _query = parseQuery(query);
`_` – конвенция для приватных свойств/методов или неиспользуемых переменных. Не вижу смысла тут использовать такой нейминг, ведь эту переменную ты как раз используешь.

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/home-page.styles.ts
> +`;
Это можно сделать с помощью компонента `Block`:

```typescript jsx
<Block padding={{ vertical: '2rem' }}>...</Block>
```

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/use-pokemons.tsx
> +    getPokemons(query)
Давай такие места форматировать красиво с пустыми строками. Читать будет сильно проще.

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/use-pokemons.tsx
> +  const [data, setData] = useState(initPokemons ?? []);
`({ initPokemons = [] })`

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/use-pokemons.tsx
> +      .catch((e: Error) => setError(e));
Мы вроде договорились использовать `async/await`. В `useEffect` этого можно добиться с помощью IIFE:

```typescript
useEffect(() => {
  (async () => { ... })();
});
```

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/use-pokemons.tsx
> +      .catch((e: Error) => setError(e));
В таких местах (39 строка) можно применять функцию сразу: `.catch(setError)`

2021-03-03 10:59 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/use-pokemons.tsx
> +        setLoading(false);
`setLoading` надо в не зависимости от результата вызывать внутри `.finally`

2021-03-03 12:49 UTC, faramozzayw commented
#### 📝Changed routes:



- [**/api/pocklist**](https://pokemon-7azxjc50l-faramozayw.vercel.app/api/pocklist)



Commit ac18008878549fa5fdef62f531651291ef3ab984 (https://pokemon-7azxjc50l-faramozayw.vercel.app).

2021-03-03 13:16 UTC, drizzer14 requested changes

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/api.ts
> +      res.status(405).end(`Method ${method} Not Allowed`);
Давай для читаемости заворачивать кейсы в блоки `{}`

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/api.ts
> +      res.status(200).json(pokemons);
Если ты обрабатываешь покемонов только для гет-запросов, то зачем идти за ними во всех остальных случаях? Не кажется странным?

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/home-page.component.tsx
> +          {/* @ts-ignore `ts(2339)` */}
Напиши пояснение, почему заигнорил. Код ошибки в данном случае ни о чём не говорит.

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/home-page.component.tsx
> +          {({ increaseOffset, data: pokemons, loading }) => {
`loading` это состояние загрузки? Булевая переменная? Если да, то `isLoading` is the way to go.

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/home-page.props.ts
>      const pokemons = responses.map(({ data }) => data);
Второй раз уже встречаю этот кусок кода.

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/pokemons.store.tsx
> +import axios from 'axios';
Спробуйте ще.

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/pokemons.store.tsx
> +interface PokemonsProviderProps {
`Provider` -> `Store`

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/pokemons.store.tsx
> +    } catch (e) {
Сокращение названий переменных – зло во плоти

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/pokemons.store.tsx
>    useUpdateEffect(() => {
Ради упражнения можешь сделать `useUpdateEffectAsync` ;)

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/utils.ts
> +  return `limit=${limit}&offset=${offset}`;
Не то же ли самое делает функция `queryToString`?

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/utils.ts
> +  return process.env.API_URL + `/pokemon?${queryToString(query)}`;
Давай договоримся не использовать конкатенацию строк через оператор `+`. Для этого пацаны придумали шаблонные строки.

2021-03-03 13:16 UTC, drizzer14 commented on src/client/routes/pocklist/index.ts
> +export { getServerSideProps } from './home-page.props';
Пустая строка в конце потерялась.

2021-03-03 13:53 UTC, faramozzayw commented
#### 📝Changed routes:



- [**/api/pocklist**](https://pokemon-in6lht6v2-faramozayw.vercel.app/api/pocklist)



Commit 023d1a57a16d97df5ea780cd407f34556ce3ecb4 (https://pokemon-in6lht6v2-faramozayw.vercel.app).

2021-03-04 08:32 UTC, drizzer14 requested changes

2021-03-04 08:32 UTC, drizzer14 commented on src/client/routes/pocklist/api.ts
> +const getPokemons = async (req: NextApiRequest, res: NextApiResponse) => {
`getPokemons: NextApiHandler`

2021-03-04 08:32 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/pokemons.store.tsx
> +      setData((prevPokemons) => [...prevPokemons, ...newPokemons]);
Добавь эту функцию в зависимости, у тебя из-за её отсутствия там не обновляется список, потому что ты не обновляешь `prevPokemons`

2021-03-04 08:32 UTC, drizzer14 commented on src/client/routes/pocklist/hooks/pokemons.store.tsx
> +    try {
Раздели пустой строкой

2021-03-04 08:32 UTC, drizzer14 commented on src/client/shared/hooks/use-update-effect-async.ts
> +      }
Оставь эффект только асинхронным. Смысл тогда делать отдельный хук с названием `Async`, если ты всё равно принимаешь синхронные эффекты?

2021-03-04 08:32 UTC, drizzer14 commented on src/client/shared/hooks/use-update-effect-async.ts
> +
Тут бы ещё где-то добавить отписку от эффекта. Банально реджектнуть промис, который происходит после анмаунта.

2021-03-04 08:43 UTC, faramozzayw commented
#### 📝Changed routes:



- [**/api/pocklist**](https://pokemon-iskityybn-faramozayw.vercel.app/api/pocklist)



Commit f0f9f099b424889420545d5ba19d13fbc50468c1 (https://pokemon-iskityybn-faramozayw.vercel.app).

2021-03-04 08:52 UTC, faramozzayw commented
#### 📝Changed routes:



- [**/api/pocklist**](https://pokemon-dw4micsjj-faramozayw.vercel.app/api/pocklist)



Commit a1caef59cc44d968cfea159fda9889b2a7b54b63 (https://pokemon-dw4micsjj-faramozayw.vercel.app).

2021-03-04 13:08 UTC, faramozzayw commented
#### 📝Changed routes:



- [**/api/pocklist**](https://pokemon-nyj73voxv-faramozayw.vercel.app/api/pocklist)



Commit 876ba5ff750eae1eed4351b40ed041d81be87f8e (https://pokemon-nyj73voxv-faramozayw.vercel.app).

2021-03-04 13:23 UTC, drizzer14 requested changes

2021-03-04 13:23 UTC, drizzer14 commented on src/client/routes/pocklist/api.ts
> +  return pokemons;
Тут можно покемонов в одну итерацию получить.

```typescript
return Promise.all(results.map(async ({ url }) => {
  return (await axios.get<Pokemon>(url.slice(0, -1))).data;
}));
```

2021-03-04 13:23 UTC, drizzer14 commented on src/client/shared/hooks/use-update-effect-async.ts
> +        Promise.reject(new Error('Component did unmout'));
Опечатка

2021-03-04 13:23 UTC, drizzer14 commented on src/client/shared/utils/createPagingUrl.ts
> +};
Правила именования файлов распространяются на все файлы

2021-03-04 13:23 UTC, drizzer14 commented on src/client/shared/utils/queryToString.ts
> +import { Query } from 'client/shared/entity';
`import type`

2021-03-04 13:37 UTC, faramozzayw commented
#### 📝Changed routes:



- [**/api/pocklist**](https://pokemon-2yb5livar-faramozayw.vercel.app/api/pocklist)



Commit 1e335850b3f4993246fd5ef1fbd4aa25a74b9099 (https://pokemon-2yb5livar-faramozayw.vercel.app).

2021-03-04 13:40 UTC, drizzer14 approved these changes

2021-03-04 13:40 UTC, merged